language: scala
scala:
    - 2.11.8
branches:
    only:
        - ma
before_script: cd Veritas
before_install:
  - sudo apt-get install -y graphviz
script:
    - sbt 'test-only *.lemmagen.*'
notifications:
    email: false
